# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'rn_Course_try_two' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for rn_Course_try_two

  # Stripe
  pod 'Stripe', '~> 14.0.0'
  pod 'ReactNativePermissions', :path => '../node_modules/react-native-permissions'

end
